Update print method to support python 3+ syntax (#272)
The following error is seen when running exercising the code in
python 3.6 environment:
   SyntaxError: Missing parentheses in call to 'print'

Signed-off-by: Richard J. Knight <rjknight@us.ibm.com>