fix(pyramidROIAlignPlugin): assertions used not existing members
Apparently, the plugin members used in the assertions where replaced by
local variables.

I also assume that `PluginField::size` was renamed to `PluginField::length`

This fixes the following compilation errors when compiling in debug mode
```
/home/stephan/projects/TensorRT/plugin/pyramidROIAlignPlugin/pyramidROIAlignPlugin.cpp:91:20: error: use of undeclared identifier 'mPooledSize'; did you mean 'pooledSize'?
            assert(mPooledSize >= 1);
                   ^~~~~~~~~~~
                   pooledSize
/usr/include/assert.h:93:27: note: expanded from macro 'assert'
     (static_cast <bool> (expr)                                         \
                          ^
/home/stephan/projects/TensorRT/plugin/pyramidROIAlignPlugin/pyramidROIAlignPlugin.cpp:68:9: note: 'pooledSize' declared here
    int pooledSize = 7;
        ^
/home/stephan/projects/TensorRT/plugin/pyramidROIAlignPlugin/pyramidROIAlignPlugin.cpp:96:30: error: no member named 'size' in 'nvinfer1::PluginField'
            assert(fields[i].size == 2);
                   ~~~~~~~~~ ^
/usr/include/assert.h:93:27: note: expanded from macro 'assert'
     (static_cast <bool> (expr)                                         \
                          ^~~~
/home/stephan/projects/TensorRT/plugin/pyramidROIAlignPlugin/pyramidROIAlignPlugin.cpp:127:20: error: use of undeclared identifier 'mSamplingRatio'; did you mean 'samplingRatio'
?
            assert(mSamplingRatio >= 0);
                   ^~~~~~~~~~~~~~
                   samplingRatio
/usr/include/assert.h:93:27: note: expanded from macro 'assert'
     (static_cast <bool> (expr)                                         \
                          ^
/home/stephan/projects/TensorRT/plugin/pyramidROIAlignPlugin/pyramidROIAlignPlugin.cpp:73:9: note: 'samplingRatio' declared here
    int samplingRatio = 0;
        ^
3 errors generated.
```